version: "3"
services:
  jekyll:
    image: jekyll/minimal:4.2.0
    volumes: 
      - .:/srv/jekyll
    command: jekyll serve --config _config.yml,_config.dev.yml --force_polling      
    ports:
      - 127.0.0.1:4000:4000